language: ruby
os: linux
dist: xenial
addons:
  postgresql: 9.6
rvm: 2.6.3
cache: bundler
jobs:
  include:
  - stage: "rspec"
script: bundle exec rspec
before_install:
  - sleep 1500
  - "gem install bundler"
before_script:
  - sleep 1500
  - "bundle exec rake db:create db:migrate"
notifications:
  email:
  - shairyarbaig@gmail.com
  - shairyar@travis-ci.org
  - shairyar@travis-ci.com