 language: ruby
os: osx
dist: xenial

addons:
  postgresql: 9.6

rvm: 2.6.3

cache: bundler

vm:
  size: medium

jobs:
  include:
    - os: linux
      language: c
      arch: amd64
      vm:
        size: medium
      script:
        - clang -coverage -O0 hello_world.c -o hello_world
        - ./hello_world
    - os: linux
      language: ruby
      dist: xenial
      arch: amd64
      vm:
        size: large
      script:
        - clang -coverage -O0 hello_world.c -o hello_world
        - ./hello_world
notifications:
  email:
    - shairyarbaig@gmail.com
    - shairyar@travis-ci.org
    - shairyar@travis-ci.com