jobs:
  include:
    - os: osx
      language: ruby
      arch: amd64
      vm:
        size: large
      script:
        - clang -coverage -O0 hello_world.c -o hello_world
        - ./hello_world
    - stage: "rspec"
      before_script:
        - "bundle exec rake db:create db:migrate"
  include:
    - os: osx
      language: ruby
      arch: amd64
      vm:
        size: medium
      script:
        - clang -coverage -O0 hello_world.c -o hello_world
        - ./hello_world
    - stage: "rspec"
      before_script:
        - "bundle exec rake db:create db:migrate"
