 language: ruby
os: linux
arch: amd64

addons:
  postgresql: 9.6

rvm: 2.6.3

cache: bundler

vm:
  size: x-large

jobs:
  include:
    - stage: "rspec"
      script: bundle exec rspec
      before_script:
        - "bundle exec rake db:create db:migrate"