jobs:
  include:
    - os: osx
      language: ruby
      arch: amd64
      vm:
        size: large
    - stage: "rspec"
      script: bundle exec rspec
      before_script:
        - "bundle exec rake db:create db:migrate"