    jobs:
  include:
    - os: osx
      language: ruby
      arch: arm64
      vm:
        size: medium
      script:
        - clang -coverage -O0 hello_world.c -o hello_world
        - ./hello_world