jobs:
  include:
    - os: linux
      language: ruby
      arch: amd64
      vm:
        size: large
      script:
        - clang -coverage -O0 hello_world.c -o hello_world
        - ./hello_world

